from __future__ import annotations

import json

import anthropic

import config

client = anthropic.Anthropic(api_key=config.ANTHROPIC_API_KEY)

SYSTEM_PROMPT = """You are a professional executive assistant that writes concise weekly reports.
Given a list of completed tasks and email summaries, produce a report with these sections:

## Week Summary
A concise narrative of what was accomplished and key themes (3-5 bullet points).

## Email Highlights
Notable conversations, decisions, or action items from emails (3-5 bullet points).
Skip routine/automated emails.

## Upcoming Tasks
Review the recurring and due tasks for next week. Highlight any that seem high-priority
or connect to this week's work. Note recurring tasks as such.

## Next Week Suggestions
Prioritized action items and focus areas based on the work patterns you see and upcoming tasks (3-5 items).

Write in a professional but friendly tone. Be specific—reference actual task names and email subjects."""


def generate_summary(
    tasks: list[dict], emails: list[dict], upcoming_tasks: list[dict] | None = None
) -> tuple[str, str]:
    """Return (summary_text, suggestions_text) generated by Claude."""
    user_content = f"""Here are the completed tasks this week:
{json.dumps(tasks, indent=2)}

Here are the emails received this week:
{json.dumps(emails, indent=2)}

Here are the tasks due or recurring next week:
{json.dumps(upcoming_tasks or [], indent=2)}

Please generate the weekly report."""

    message = client.messages.create(
        model="claude-sonnet-4-5-20250929",
        max_tokens=2000,
        system=SYSTEM_PROMPT,
        messages=[{"role": "user", "content": user_content}],
    )

    full_text = message.content[0].text

    # Split into summary (Week Summary + Email Highlights) and suggestions
    suggestions_marker = "## Next Week Suggestions"
    if suggestions_marker in full_text:
        idx = full_text.index(suggestions_marker)
        summary_text = full_text[:idx].strip()
        suggestions_text = full_text[idx:].strip()
    else:
        summary_text = full_text
        suggestions_text = ""

    return summary_text, suggestions_text
